//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlinaTashkhuzhaeva422_PetAndDegs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public int IdPets { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] PhotoPath { get; set; }
        public Nullable<int> IdUsers { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
