//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlinaTashkhuzhaeva422_PetAndDegs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IdUsers { get; set; }
        public Nullable<int> IdRole { get; set; }
        public Nullable<int> IdPets { get; set; }
    
        public virtual Pets Pets { get; set; }
        public virtual Role Role { get; set; }
    }
}
